sudo: required
services:
  - docker

before_install:
  - docker build -t braininfryingpan/multidocker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run braininfryingpan/multidocker-test npm test -- --coverage

after_success:
  - docker build -t braininfryingpan/multi-container-client ./client
  - docker build -t braininfryingpan/multi-container-nginx ./nginx
  - docker build -t braininfryingpan/multi-container-server ./server
  - docker build -t braininfryingpan/multi-container-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push braininfryingpan/multi-container-client
  - docker push braininfryingpan/multi-container-nginx
  - docker push braininfryingpan/multi-container-server
  - docker push braininfryingpan/multi-container-worker